import type { Metadata } from "next";
import { Geist, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { cn } from "lazy-cn";

const fontSans = Geist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-next-sans",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  // weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-next-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: ReactNode;
}) {
  return (
    <html lang="en" className={cn(fontSans.variable, fontMono.variable)}>
      <body
        className={`antialiased bg-zinc-800 text-white`}
        style={{
          '--bg': 'var(--color-zinc-800)',
          '--color-background': 'var(--bg)',
          '--color-primary': 'rgba(159, 159, 159, 1)',
        }}
      >
        {props.children}
      </body>
    </html>
  );
}
