import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";

const fontSans = Geist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-next-sans",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  // weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-next-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${ fontSans.variable } ${ fontMono.variable } antialiased`}
      >
        {props.children}
      </body>
    </html>
  );
}
